name: Authenticate Assets with CAS

on:
  workflow_dispatch:
  #push:
  #  branches: [main]
  workflow_run:
    workflows: ["Notarize Assets with CAS"]    
    types: [completed]

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  authenticate-assets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Authenticate LICENSE
        #--> Run the GitHub action
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:
          # Whatever asset is being authenticated, can be a target/ or dist/ compiled binary or any type of file
          # Your signerID is the only thing needed to authenticate assets, this can be provided in both base64 or plaintext, and will be the email address used to generate your API Key
          asset: LICENSE
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate README.md        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: README.md
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate Dockerfile        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: Dockerfile
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate HA-MQTT.md        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: HA-MQTT.md
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t 
      
      - name: Authenticate package.json        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: package.json
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate package-lock.json        
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: package-lock.json
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t

      - name: Authenticate src/commands.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/commands.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate src/diagnostic.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/diagnostic.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate src/index.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/index.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate src/logger.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/logger.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate src/measurement.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/measurement.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate src/mqtt.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/mqtt.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
      - name: Authenticate src/vehicle.js
        uses: codenotary/cas-authenticate-asset-github-action@main
        with:          
          asset: src/vehicle.js
          signerID: QmlnVGh1bmRlclNSQG91dGxvb2suY29t
